name: fruits_hub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: 'Montserrat'
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/icons.png"
    background_color: "#ffffff"
    theme_color: "#4CAF50"
flutter_intl:
  enabled: true

# flutter_assets:
#   assets_path: assets/images/
#   output_path: lib/core/utils
#   filename: assets.dart
#   field_prefix: null
